---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-client
spec:
  selector:
    matchLabels:
      app: api-client
  replicas: 1
  template:
    metadata:
      labels:
        app: api-client
    spec:
      restartPolicy: Always
      containers:
        - name: api-client
          image: api-client:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          env: # Setting Environmental Variables
            - name: USER_INFO_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: userinfoHost
            - name: USER_INFO_PORT # Setting Database password
              value: "8083"
            - name: CARS_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: carsHost
            - name: CARS_PORT # Setting Database password
              value: "8085"
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: eurekaHost
            - name: EUREKA_PORT # Setting Database password
              value: "8081"

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  ports:
    - protocol: "TCP"
      port: 8089    # The port inside the cluster
      targetPort: 8089  # The port exposed by the service
  type: LoadBalancer        # Type of service
  selector:
    app: api-client
---
