spring:
  application:
    name: gateway-Client
  cloud:
    gateway:
      routes:
        - id:  UserInfo-Service
          uri: lb://UserInfo-Service
          predicates:
              - Path=/users/**
        - id: CARS
          uri: lb://CARS
          predicates:
            - Path=/cars/**
#            - - id: Cars
#                  uri: http://${CARS_HOST}:${CARS_PORT}/
#                  predicates:
#                    - Path=/cars/**
        ## FUND TRANSFER SERVICE


server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka



